In [6]:
import numpy as np
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [7]:
arr1 = np.array([14,12,35,36])
print(arr1)

[14 12 35 36]


In [8]:
arr1.ndim

1

In [9]:
arr1.shape

(4,)

In [10]:
arr1.dtype

dtype('int32')

In [11]:
arr2 = np.array([[14,52,36,39],[78,75,42,63],[45,42,36,39]])
print(arr2)

[[14 52 36 39]
 [78 75 42 63]
 [45 42 36 39]]


In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(3, 4)

In [14]:
#creating an array that is evenly spaced
np.linspace(14,85)

array([14.        , 15.44897959, 16.89795918, 18.34693878, 19.79591837,
       21.24489796, 22.69387755, 24.14285714, 25.59183673, 27.04081633,
       28.48979592, 29.93877551, 31.3877551 , 32.83673469, 34.28571429,
       35.73469388, 37.18367347, 38.63265306, 40.08163265, 41.53061224,
       42.97959184, 44.42857143, 45.87755102, 47.32653061, 48.7755102 ,
       50.2244898 , 51.67346939, 53.12244898, 54.57142857, 56.02040816,
       57.46938776, 58.91836735, 60.36734694, 61.81632653, 63.26530612,
       64.71428571, 66.16326531, 67.6122449 , 69.06122449, 70.51020408,
       71.95918367, 73.40816327, 74.85714286, 76.30612245, 77.75510204,
       79.20408163, 80.65306122, 82.10204082, 83.55102041, 85.        ])

In [15]:
np.linspace(14,85, 20)

array([14.        , 17.73684211, 21.47368421, 25.21052632, 28.94736842,
       32.68421053, 36.42105263, 40.15789474, 43.89473684, 47.63157895,
       51.36842105, 55.10526316, 58.84210526, 62.57894737, 66.31578947,
       70.05263158, 73.78947368, 77.52631579, 81.26315789, 85.        ])

In [16]:
np.linspace(1,10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.ones((5,10)) * 2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [22]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [24]:
arr3 = np.arange(1,101, 3)
print(arr3)

[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


In [25]:
#how to generate random numbers
np.random.seed(1)
arr4 = np.random.randint(10,55,100)
arr4

array([47, 53, 22, 18, 19, 21, 15, 25, 10, 26, 11, 22, 17, 16, 35, 30, 47,
       28, 30, 21, 52, 38, 39, 24, 14, 33, 33, 51, 40, 42, 32, 23, 51, 19,
       17, 32, 11, 10, 27, 18, 34, 23, 52, 18, 40, 17, 13, 16, 31, 13, 14,
       34, 53, 22, 36, 26, 51, 28, 25, 10, 14, 35, 44, 33, 17, 36, 35, 50,
       32, 19, 13, 49, 33, 46, 37, 47, 29, 48, 18, 42, 44, 20, 33, 25, 33,
       35, 17, 38, 20, 42, 34, 33, 11, 23, 13, 10, 23, 16, 31, 16])

In [26]:
#how to convert 1d array to 2d
arr5 = arr4.reshape(10,10)
arr5

array([[47, 53, 22, 18, 19, 21, 15, 25, 10, 26],
       [11, 22, 17, 16, 35, 30, 47, 28, 30, 21],
       [52, 38, 39, 24, 14, 33, 33, 51, 40, 42],
       [32, 23, 51, 19, 17, 32, 11, 10, 27, 18],
       [34, 23, 52, 18, 40, 17, 13, 16, 31, 13],
       [14, 34, 53, 22, 36, 26, 51, 28, 25, 10],
       [14, 35, 44, 33, 17, 36, 35, 50, 32, 19],
       [13, 49, 33, 46, 37, 47, 29, 48, 18, 42],
       [44, 20, 33, 25, 33, 35, 17, 38, 20, 42],
       [34, 33, 11, 23, 13, 10, 23, 16, 31, 16]])

In [29]:
#converting back to 1d array
arr5 = arr5.flatten()
arr5

array([47, 53, 22, 18, 19, 21, 15, 25, 10, 26, 11, 22, 17, 16, 35, 30, 47,
       28, 30, 21, 52, 38, 39, 24, 14, 33, 33, 51, 40, 42, 32, 23, 51, 19,
       17, 32, 11, 10, 27, 18, 34, 23, 52, 18, 40, 17, 13, 16, 31, 13, 14,
       34, 53, 22, 36, 26, 51, 28, 25, 10, 14, 35, 44, 33, 17, 36, 35, 50,
       32, 19, 13, 49, 33, 46, 37, 47, 29, 48, 18, 42, 44, 20, 33, 25, 33,
       35, 17, 38, 20, 42, 34, 33, 11, 23, 13, 10, 23, 16, 31, 16])

In [30]:
np.mean(arr5)

28.69

In [31]:
np.median(arr5)

28.0

In [32]:
np.sum(arr5)

2869

In [33]:
#std-standard deviation
np.std(arr5)

12.359364870413042

In [34]:
np.var(arr5)

152.7539

In [35]:
np.sqrt(arr5)

array([6.8556546 , 7.28010989, 4.69041576, 4.24264069, 4.35889894,
       4.58257569, 3.87298335, 5.        , 3.16227766, 5.09901951,
       3.31662479, 4.69041576, 4.12310563, 4.        , 5.91607978,
       5.47722558, 6.8556546 , 5.29150262, 5.47722558, 4.58257569,
       7.21110255, 6.164414  , 6.244998  , 4.89897949, 3.74165739,
       5.74456265, 5.74456265, 7.14142843, 6.32455532, 6.4807407 ,
       5.65685425, 4.79583152, 7.14142843, 4.35889894, 4.12310563,
       5.65685425, 3.31662479, 3.16227766, 5.19615242, 4.24264069,
       5.83095189, 4.79583152, 7.21110255, 4.24264069, 6.32455532,
       4.12310563, 3.60555128, 4.        , 5.56776436, 3.60555128,
       3.74165739, 5.83095189, 7.28010989, 4.69041576, 6.        ,
       5.09901951, 7.14142843, 5.29150262, 5.        , 3.16227766,
       3.74165739, 5.91607978, 6.63324958, 5.74456265, 4.12310563,
       6.        , 5.91607978, 7.07106781, 5.65685425, 4.35889894,
       3.60555128, 7.        , 5.74456265, 6.78232998, 6.08276

In [36]:
np.cos(arr5)

array([-0.99233547, -0.91828279, -0.99996083,  0.66031671,  0.98870462,
       -0.54772926, -0.75968791,  0.99120281, -0.83907153,  0.64691932,
        0.0044257 , -0.99996083, -0.27516334, -0.95765948, -0.90369221,
        0.15425145, -0.99233547, -0.96260587,  0.15425145, -0.54772926,
       -0.16299078,  0.95507364,  0.26664293,  0.42417901,  0.13673722,
       -0.01327675, -0.01327675,  0.7421542 , -0.66693806, -0.39998531,
        0.83422336, -0.53283302,  0.7421542 ,  0.98870462, -0.27516334,
        0.83422336,  0.0044257 , -0.83907153, -0.29213881,  0.66031671,
       -0.84857027, -0.53283302, -0.16299078,  0.66031671, -0.66693806,
       -0.27516334,  0.90744678, -0.95765948,  0.91474236,  0.90744678,
        0.13673722, -0.84857027, -0.91828279, -0.99996083, -0.12796369,
        0.64691932,  0.7421542 , -0.96260587,  0.99120281, -0.83907153,
        0.13673722, -0.90369221,  0.99984331, -0.01327675, -0.27516334,
       -0.12796369, -0.90369221,  0.96496603,  0.83422336,  0.98

In [37]:
np.percentile(arr5,45)

25.0